# Note: Not used; the rules must be embedded directly in config-map.yml rules.

groups:
- name: all-instances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Instance is down
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'

- name: kubernetes-probes
  rules:
  - alert: KubePodProbeFailed
    expr: kube_pod_status_ready{condition="false"} == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Pod {{ $labels.pod }} probe failed"
      description: "The readiness/liveness probe for Pod {{ $labels.pod }} in Namespace {{ $labels.namespace }} has been failing for more than 1 minute."

- name: kubernetes-resource-exhaustion
  rules:
  - alert: KubePodOutOfMemory
    expr: sum(rate(container_memory_usage_bytes{container!="", container!="POD"}[1m])) by (namespace, pod) > (container_spec_memory_limit_bytes{container!="", container!="POD"} * 0.8)
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in Namespace {{ $labels.namespace }} is running out of memory"
      description: "Memory usage for Pod {{ $labels.pod }} in Namespace {{ $labels.namespace }} is above 80% of its limit for more than 1 minute."

  - alert: KubePodDiskSpaceCritical
    expr: (kubelet_volume_stats_available_bytes{persistentvolumeclaim!=""} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!=""}) < 0.1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Disk space is critically low for Pod {{ $labels.pod }} in the Namespace {{ $labels.namespace }}"
      description: "Available disk space for Pod {{ $labels.pod }} in the Namespace {{ $labels.namespace }} is below 10%."
